#!/bin/sh

update() {
  # extract installed version
  current=$(cat /var/nanobox/nanobox-server.md5)

  # download the latest checksum
  curl \
    -k \
    -s \
    -o /var/nanobox/nanobox-server.md5
    https://s3.amazonaws.com/tools.nanobox.io/server/linux/amd64/nanobox-server.md5

  # compare versions
  latest=$(cat /var/nanobox/nanobox-server.md5)

  if [ ! "$current" = "$latest" ]; then
    # get the latest server binary
    curl \
      -k \
      -s \
      -o /usr/local/bin/nanobox-server
      https://s3.amazonaws.com/tools.nanobox.io/server/linux/amd64/nanobox-server
  fi
}

case "${1}" in
  start)
    update
    /usr/local/bin/nanobox-server/nanobox-server >> /var/log/nanoboxd.log 2>&1 &
    ;;

  stop)
    pkill nanobox-server
    ;;

  status)
    pidof -o %PPID nanobox-server
    ;;

  *)
    echo "Supported options [start|status|stop]"
    exit 1
    ;;
esac
