#!/bin/sh

case "${1}" in
  start)
    /usr/local/bin/nanobox-server/nanobox-server >> /var/log/nanoboxd.log 2>&1 &
    ;;

  stop)
    pkill nanobox-server
    ;;

  status)
    pidof -o %PPID nanobox-server
    ;;

  *)
    echo "Supported options [start|status|stop]"
    exit 1
    ;;
esac
